### PR TITLE
Feature: Add textarea for adding co-authors to talks by email address.

### PR DESCRIPTION
**Pull request by iSOLveIT**
This fixes issue #10.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@iSOLveIT you dont need to add co-authors. A talk can already have multiple authors. Better use that feature! See in schedule we are already displaying multiple authors for a field

**Comment by Abdur-rahmaanJ** [comment]
Just we did not have any way of adding through the UI but the functionality already exists

**Comment by iSOLveIT** [comment]
> @iSOLveIT you dont need to add co-authors. A talk can already have multiple authors. Better use that feature! See in schedule we are already displaying multiple authors for a field

1. I know a talk can already have multiple authors with is stored in the talk_list_author_bridge table.
2. I retrieved co_authors from the talk_list_author_bridge table.
3. I added the co_authors Textarea column to the Talk model to provide a way to add and edit co_authors through the UI. 
4. I want to know if I shouldn't store the co_authors in the Talks table in the database.

In all, I would appreciate it if you can explain your comments enough for me to understand. Thanks

**Comment by Abdur-rahmaanJ** [comment]
In sum : dont add the co-author attribute to model but use existing bridge. Ui or not, it is possible to list via bridge. Like in schedule we do:

```
{% for author in talk.author_list.authors %}
                            {{author.first_name}} {{author.last_name}},
                        {% endfor %}
```

I understand your use case but i request you to be creative and use the bridge to solve it

**Comment by iSOLveIT** [comment]
> In sum : dont add the co-author attribute to model but use existing bridge. Ui or not, it is possible to list via bridge. Like in schedule we do:
> 
> ```
> {% for author in talk.author_list.authors %}
>                             {{author.first_name}} {{author.last_name}},
>                         {% endfor %}
> ```
> 
> I understand your use case but i request you to be creative and use the bridge to solve it

Thank you for your review. I have used the talk.author_list.authors and I have managed to solve most issues.
The issue I have facing is adding a way to add and edit the author_list in the UI.
I am suggesting a possible solution. I wan to build a route that handles adding and editing a talk_author_list without updating the entire talk through the edit_talk route.

**Comment by Abdur-rahmaanJ** [comment]
Use a select or multi checkboxes with the emails or ids of the users as hidden fields that you can retrieve on posting

**Comment by iSOLveIT** [comment]
> Use a select or multi checkboxes with the emails or ids of the users as hidden fields that you can retrieve on posting

okay thanks

**Pull request closed without merging**
